### ISSUE TITLE
Code-intelligence suggestions becoming dark

### ISSUE THREAD

**Issue by rohan-paul** [maykbrito/theme-launchbase#2]
Hi, 

Absolutely great theme, however the code-intelligence suggestions are becoming dark. For example, in below screenshot the first suggestion is almost not visible.

![image](https://user-images.githubusercontent.com/12703975/138948303-63dc87df-4bd8-4c50-929f-6187a63470df.png)

**Comment by maykbrito** [comment]
Hi Rohan!

Thanks for helping on this one!

I'll take a look and make it better 💜

**Comment by maykbrito** [comment]
Fixed in the last commit

**Comment by rohan-paul** [comment]
Working awesome now. Thanks so much @maykbrito ..
